steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-springboot', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/react-springboot']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'my-cloud-run-service', '--image', 'gcr.io/$PROJECT_ID/react-springboot', '--region', 'europe-west4', '--allow-unauthenticated', '--add-cloudsql-instances', 'vic-personal:europe-west4:bharvest']
images:
- gcr.io/$PROJECT_ID/react-springboot